# Generated by Django 2.0.7 on 2018-07-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('COE', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
                ('employeeID', models.CharField(max_length=10)),
                ('parentID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=250)),
                ('teamID', models.CharField(max_length=50)),
                ('deparment', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Team'),
        ),
    ]
