# Generated by Django 2.0.7 on 2018-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180717_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teamID',
        ),
        migrations.AddField(
            model_name='employee',
            name='alma_mater',
            field=models.CharField(default='James Madison University', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
